### ISSUE TITLE
Application error on desktop install

### ISSUE THREAD

**Issue by Biodagar** [grocy/grocy-desktop#11]
I installed Grocy on Windows 10, and the installation appeared to function fine. It just won't run for some reason and I don't know anything about programming so can't solve the problem.

Type: PDOException
Code: 23000
Message: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: users.username
File: \grocy-desktop\grocy\vendor\morris\lessql\src\LessQL\Database.php
Line: 606

Have attached screenshots of the trace.

![grocy-error-screenshot2](https://user-images.githubusercontent.com/9072491/77380241-917e0d00-6dca-11ea-9877-70e603594965.png)
![grocy-error-screenshot1](https://user-images.githubusercontent.com/9072491/77380246-92af3a00-6dca-11ea-80ef-100e6badb3d2.png)

**Comment by berrnd** [comment]
I've moved it to the right repository...

**Comment by rpbx** [comment]
Hello @berrnd ,

First, I would like to thank you. This is a genius concept and I hope it'll work for me. I came across this project through HomeAssistant. It does not work very well on their app, which led me to install it on my desktop and I am having the same issue.

**Comment by berrnd** [comment]
Haven't had time to try to reproduce it yet, otherwise you could read the solution here...

If it's a new installation, maybe just try to restart by deleting `C:\Users\<USERNAME>\AppData\Roaming\grocy-desktop\grocy-data\grocy.db`.

Most probably it's just a timing problem / timeout - is it maybe a "slower" machine on your side?

**Comment by rpbx** [comment]
The machine is an I7 

"If it's a new installation, maybe just try to restart by deleting C:\Users\<USERNAME>\AppData\Roaming\grocy-desktop\grocy-data\grocy.db."

Deleting the db fixed it.

Thank you.

**Comment by berrnd** [comment]
Ok, so was an incomplete database migration, however that happended.

@Biodagar please also try that and feel free to reopen if the problem persists.

**Comment by Biodagar** [comment]
@berrnd Thanks for that. It restarted the application but it threw another error. Have attached the screenshot for you. Let me know if you want to see the trace?
![20200328-grocy](https://user-images.githubusercontent.com/9072491/77815763-4edf6c00-710d-11ea-834b-2e6bc3d25272.png)

**Comment by berrnd** [comment]
Seems to be a similar problem. The mentioned missing table is the first one created when starting a new database. Maybe the application was open while you deleted the file?

However, I'll check and try how to increase timeout problems, which most probably is the cause for this.

If nothing works, in the attached ZIP is an empty database file of the latest grocy version, just put that in `C:\Users\<USERNAME>\AppData\Roaming\grocy-desktop\grocy-data\grocy.db`:

[grocy.zip](https://github.com/grocy/grocy-desktop/files/4396764/grocy.zip)

**Comment by Biodagar** [comment]
@berrnd Nope, application was closed.

I took your suggestion about thinking perhaps it was the machine, and went to install it on a separate machine from the Windows store. That failed. So I deleted the program and went to reinstall it from the files at grocy.info and that failed as well. 

Thinking perhaps I should just give using this software a miss?

**Comment by berrnd** [comment]
Always the same error? I will to some tests later and also increase those timeouts I mentioned which may be the problem.

**Comment by berrnd** [comment]
I tried to tweak the PHP configuration and also added a menu entry (grocy -> Recreate database) to recreate the database from within the GUI.

If you want to try it, please replace the files from the attached ZIP:
- `php.ini` goes into `C:\Users\<USERNAME>\AppData\Roaming\grocy-desktop\runtime-dependencies\1.6.0.0\php`
- `grocy-desktop.exe` goes into `C:\Users\<USERNAME>\AppData\Local\grocy-desktop`

[grocy-desktop.zip](https://github.com/grocy/grocy-desktop/files/4398826/grocy-desktop.zip)

**Comment by Biodagar** [comment]
No, different errors. I'll go grab screenshots for you.
