### ISSUE TITLE
Guessed grocy localization is wrong for "subculture" languages

### ISSUE THREAD

**Issue by os4coelhos** [grocy/grocy-desktop#14]
I've tried ti install grocy on 2 diferente laptops but keep getting the same error. Used the cllassic installer and "get it from Microsoft" with the same results :(

Slim Application Error
The application could not run because of the following error:

Details
Type: InvalidArgumentException
Code: 0
Message: 'C:\Users\harc1\.grocy-desktop\grocy\services/../localization/pt/chore_period_types.po' is not a valid file
File: C:\Users\harc1\.grocy-desktop\grocy\vendor\gettext\gettext\src\Extractors\Extractor.php
Line: 37

**Comment by os4coelhos** [comment]
Got it to work.
...\AppData\Roaming\grocy-desktop\grocy\localization -> had 2 folders for Portuguese (pt_BR and pt_PT).
Changed the name of one of the to "pt" and it's working.

**Comment by berrnd** [comment]
Thanks for finding that, I renamed this issue to track the underlying problem here.

**Comment by os4coelhos** [comment]
@berrnd thank you for your passion and for sharing grocy with the rest of the world.
Best regards
