### ISSUE TITLE
Grocy was working fine, but  now it opens with a blank window and no user interface?

### ISSUE THREAD

**Issue by scottjanousek** [grocy/grocy-desktop#16]
I've had this happen twice ... I am running Windows 10 and the standalone app. The first time I installed the native version it was doing the same thing ... displaying an empty window ... then I reloaded and tried a bunch of things ... eventually it DID work and I started to make entries ... now after a couple weeks I tried loading it and it's back to displaying an empty window ... doesn't matter how long I wait, so I don't think it's trying to load anything ... also I rebooted twice so that's not it ... Not sure what it could be. I will try a reinstall if I don't hear back soon. Just wanted to let you know so you can track a potential issue. If I view source in the window it's just: "<html><head></head><body></body></html>" BTW. No other apps are running that I can see that might interfere.
![grocybug](https://user-images.githubusercontent.com/205682/79367344-b4a86200-7f1b-11ea-91bb-82eee3e87f2a.png)

**Comment by berrnd** [comment]
I transfered this to the right repo...

Basically, grocy-desktop just manages a webserver in the background, see the Help/Debug menu to show the process outputs, maybe a hint for the problem can be found there...

**Comment by scottjanousek** [comment]
Thanks. I posted the html being returned from the server ... and I grabbed this PHP server output in the windows frame UI.

[Wed Apr 15 14:31:59 2020] PHP 7.4.3 Development Server (http://localhost:54436) started

**Comment by scottjanousek** [comment]
Maybe it's the database ... I do appear to still have data that I backed up. I haven't really done any major installations recently.

**Comment by berrnd** [comment]
So no error message so far, however, maybe something of the dependencies for the embedded browser is broken, then a reinstall would help, you can also try to access the in the PHP server output mentioned URL from any other browser on the same machine...

Currently grocy-desktop is also totally reworked, nginx is embedded and used as the webserver for example instead of the PHP built-in develpment server as of now. Maybe this will also improve stability - it should be ready in the next days...

**Comment by scottjanousek** [comment]
Hi Bernd. So the root cause is likely having Avira Phantom VPN turned on before running grocy. When I turn it off, grocy seems to work fine. Maybe it's messing the internal server with a hosts file or proxy somehow ...

**Comment by berrnd** [comment]
Ok, great that you've found the cause. The webserver of grocy-desktop currently only listens on the localhost/loopback interface, whatever that VPN software messes up with that network adapter...
