### ISSUE TITLE
Unhandled error occurred

### ISSUE THREAD

**Issue by smaughan** [grocy/grocy-desktop#23]
After a fresh install at first start up, I received this error: 

**Exception Name:** 
FileNotFoundException

**Exception Message:** 
Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found.

**Exception Stacktrace:** 
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at GrocyDesktop.Program.CurrentDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)

**Comment by berrnd** [comment]
This is not really something I can help with.
The mentioned DLL is shipped with the installer, most probably it gets blocked by your anti malware software or something.

Please double check that.

Should be located at (after the first start of grocy) at `C:\Users\<USERNAME>\AppData\Roaming\grocy-desktop\runtime-dependencies\1.8.1.0\cef\x86`.

Maybe try to restart by deleting the whole `C:\Users\<USERNAME>\AppData\Roaming\grocy-desktop\runtime-dependencies` folder.

**Comment by llewy** [comment]
For what it's worth; 

CefSharp has a few dependencies:
Microsoft .NET 4.5.2 or greater
Visual C++ Runtime 2015 or greater. (VC++ 2017 and VC++ 2019 are backwards compatible)

**Comment by berrnd** [comment]
> CefSharp has a few dependencies:
> Microsoft .NET 4.5.2 or greater
> Visual C++ Runtime 2015 or greater. (VC++ 2017 and VC++ 2019 are backwards compatible)

Thanks for mentioning that.

I've also read the CefSharp docs and maybe that's why the installer exactly requires / grocy-desktop has bundled exactly that.

**Comment by llewy** [comment]
I think I wasn't clear, I had the same error as above and after manually installing the C++ Runtime, the error was gone.

**Comment by berrnd** [comment]
Can't be the case, all the needed dependencies are shipped/included.

Can also be easily reproduced by taking a fresh Windows VM or something, it will work, I always test exactly that after updating CefSharp for grocy-desktop.

In all those cases (not only for grocy-desktop, more generally), it was about that some fancy antimalware tools block or delete some DLLs, however. And however someone uses such fancy tools, I'll also never get behind that...

**Comment by llewy** [comment]
I've found the issue. There was already an installation of the Runtime, but the x64-version, which obviously doesn't work on an x86-system. Maybe Grocy sees Runtime is installed, but can't/doesn't check if it's the right version for the system? 

Anyway, got it fixed, thanks for the very nice piece of software.

**Comment by berrnd** [comment]
x64 and x86 runtimes can of course co-exist on the same system, grocy-desktop is a x86 application and also only bundles Cef x86 - and x86 programs can't even technically use x64 DLLs. So also can't be really the source for this problem...
