### ISSUE TITLE
Unable to run grocy: PHP module 'intl' not installed, but required.

### ISSUE THREAD

**Issue by tfont** [grocy/grocy-desktop#29]
Happened after updating.

**Comment by berrnd** [comment]
Answered in https://github.com/grocy/grocy/issues/1543#issuecomment-884147738.

**Comment by tfont** [comment]
This error is occurring because the PHP extension intl is required - I could imagine better string byte support (multiple languages and specific character sets).

This is error takes place because the intl extension is not automatically bundled properly when a user 'updates' directly from the desktop version. Let me make that clear "updates directly from the desktop version".
1. not updated in the PHP ini configuration when updating
2. not included in the extension folder (properly downloaded and registered as stated above) when updating.

Because of this, after the app is updated, it is no longer usable as the extension is fails to load.

Currently solution: To redownload and reinstall grocy desktop from the latest manual download. This solution makes the 'updating' feature broken, therefore, a bug.

**Comment by berrnd** [comment]
Now I finally get it, why not describe it in that understandable manner just right away?

So you used grocy-desktop v1.9.0, upgraded _only_ grocy to v3.1.0 and then it does not run with that message.
That's of course the thing...

From time to time, dependencies change (also for Barcode Buddy, was the same about the `redis` extensions for this grocy-desktop release).

As you also noted, simply upgrading also grocy-desktop to the latest version fixes this / such situations.

The only way would be to restrict grocy-desktop to a specific grocy (and Barcode Buddy) release.

This is known, easily fixable (by upgrading grocy-desktop as you also did; if there is a supporting release already), so not a problem.

If you have an idea to manage (arbitrary) runtime dependencies automatically without restricting grocy-desktop to a specific grocy release, let me know.
