### ISSUE TITLE
Blank Screen Windows 10

### ISSUE THREAD

**Issue by dieselman8228** [grocy/grocy-desktop#30]
I apologize if this has been posted and I missed it. I have been running Grocy on windows 10 for several months with no problems. I started it this morning and the program opened but the only thing displayed was the top tool bar that says File Grocy and Barcode Buddy. Windows firewall asked me to allow it which Did, but even after restarting the computer it does not work. I disabled the fire wall and it changed my connection port but did not allow the program to run just the white screen. Any help would be appreciated. Also, is there a comprehensive guide to creating a linux server. I am handy with linux but clueless with docker. Thanks in advance and for your hard work. My wife LOOOVES grocy.

**Comment by berrnd** [comment]
Have you checked [the note about exactly that in the release notes](https://github.com/grocy/grocy-desktop/releases/tag/v1.10.0) and doesn't that help?

> ⚠️ If you upgrade from a previous version, please update grocy manually after the first start if you just get a white screen (grocy -> Update in the top menu bar)

&nbsp;

> I am handy with linux

Quoting myself from grocy/grocy#1538:

> See [grocy.info/links](https://grocy.info/links) or [grocy/docs](https://github.com/grocy/docs) or https://www.reddit.com/r/grocy/comments/ka1hy5.
>
> All of that is not maintained by me.
> I would highly recommend using something like the [Docker Images](https://github.com/grocy/grocy#how-to-run-using-docker), [grocy-desktop](https://github.com/grocy/grocy-desktop) or the [Home Assistant integration](https://github.com/hassio-addons/addon-grocy), if you're not so familiar with setting up webservers. grocy is definitely technically a pretty simple PHP application, so any tutorial for setting up those will basically fit.

**Comment by dieselman8228** [comment]
Thank you for the help and sorry I missed that post

**Comment by berrnd** [comment]
Ok, no problem - so closing this, if it doesn't help/work, however, feel free to reopen.
