### ISSUE TITLE
Getting an error during installation and initial setup  - Bug: 

### ISSUE THREAD

**Issue by Shredder5262** [grocy/grocy-desktop#31]
First time installing on this machine. I have verified that the file it is complaining about does exist at 
..\AppData\Roaming\grocy-desktop\runtime-dependencies\1.10.0.0\cef\x86\
i have tried running the app as admin, I have tried to repair the installation. No joy. Please advise.

![08-01-2021 -  18_07_12 - Window](https://user-images.githubusercontent.com/59770346/127788034-461ec86b-3761-48ad-ac52-ec6802954ae4.png)

**Comment by berrnd** [comment]
This is not really something I can help with.
The mentioned DLL is shipped with the installer, most probably it gets blocked by your anti malware software or something.
When searching for it, that's a not so uncommon problem with [CefSharp](https://cefsharp.github.io/) (the web browser component used).

Please double check that.

Should be located at (after the first start of grocy) at `C:\Users\<USERNAME>\AppData\Roaming\grocy-desktop\runtime-dependencies\1.10.0.0\cef\x86`.

Maybe try to restart by deleting the whole `C:\Users\<USERNAME>\AppData\Roaming\grocy-desktop\runtime-dependencies` folder.

Exactly the same "problem" as #23.

**Comment by Shredder5262** [comment]
ok, thanks for the response, I will check and circle back

**Comment by Shredder5262** [comment]
Please do not close this until it is solved

**Comment by berrnd** [comment]
> Please do not close this until it is solved

This is definitely not a bug, this is the issue tracker - we have the [/r/grocy subreddit](https://www.reddit.com/r/grocy/) for general help requests.

**Comment by Shredder5262** [comment]
I just checked the AV (Windows Defender software, nothing being blocked.  I removed the dependencies folder as you suggested and tried to re-run, same issue. I completely removed the folder from the appdata folder.  Same result after downloading and reinstalling

**Comment by berrnd** [comment]
Whatever, the file is shipped, the file exists (like you said you've also verified), it works here and for many others - so what do you expect I should do? Magic tricks are not yet part of my portfolio...
