### ISSUE TITLE
Feature Request: Use hostname/IP for grocy URLs when external access is enabled

### ISSUE THREAD

**Issue by frohlichcortezh** [grocy/grocy-desktop#34]
First I'd like to thanks for all the work on the app. I'm just starting but good job :D

I installed the Windows App from the Microsoft Store today and activated the external access on the app.
Although when I created the API key the QR Code generates a localhost URL, so I can't use it on the [Android App](https://github.com/patzly/grocy-android).

Could be nice to have the corrected IP since its shown on the Win App.

v1.11.0.0

**Comment by berrnd** [comment]
grocy-desktop is supposed to be "just works" alternative way to run grocy (on Windows) if you want to use grocy (as a single user) just like a normal application. Everything related to config options and more is managed automatically and e.g. authentication is disabled (so please really don't open this up to the internet and only use it in a trusted local network).

However, I don't know how you come to the conclusion that this is a bug, it's just not done so far - so can be of course added / is a feature request.

**Comment by frohlichcortezh** [comment]
My bad for the conclusion of a bug instead of a feature ;)

**Comment by berrnd** [comment]
When external access is enabled, all URLs are now based on the external (IP based) hostname.
