### ISSUE TITLE
Bug: Fresh installation errors - "ArgumentException", "NullReferenceException", "InvalidOperationException"

### ISSUE THREAD

**Issue by AtomicClown** [grocy/grocy-desktop#39]
Hello, apologies if this is somehow redundant or invalid but I've scoured the _Issues_ section for a solution and haven't found one thus far.

I installed Grocy-Desktop on my Windows 10 PC today, but the application opens with a completely blank window and an error occurrence of **"Item has already been added. Key in dictionary: 'PHP_FCGI_MAX_REQUESTS'  Key being added: 'PHP_FCGI_MAX_REQUESTS'".**

Anything I select in the application produces an error message, even when I try to close the app itself.
![Screenshot_1](https://user-images.githubusercontent.com/43078569/164971200-4e314f31-be31-424f-8575-db73bccd812b.png)
![Screenshot_2](https://user-images.githubusercontent.com/43078569/164971206-9d4610c4-7c1f-49bd-8cfb-ecbaf0839742.png)
![Screenshot_3](https://user-images.githubusercontent.com/43078569/164971209-3d4dba87-7ca3-4277-8be3-0704d23b87a4.png)

I've tried everything from reinstalling with all malware protection disabled, running with my VPN disabled, adding exceptions in my firewall, installing previous versions, installing from the Microsoft Store instead, etc.

Again, I'm sorry if this is somehow invalid, I've never really posted a bug report before. I just want to figure out a way to make it work.

**Comment by berrnd** [comment]
A problem needs to be reproducible to being able to fix it. I can't reproduce it by what's provided - just tried to install the latest release on a fresh Windows 10 system, works:

https://user-images.githubusercontent.com/2161815/164972389-a569893b-79b2-42ad-8dfd-580954268271.mp4

&nbsp;
> I've tried everything from reinstalling with all malware protection disabled, running with my VPN disabled, adding exceptions in my firewall, installing previous versions

At least the first error message is completely unrelated to any of this, it's related to this line:
https://github.com/grocy/grocy-desktop/blob/092fd3ff032b7ec5619dca467cbfb1e18b33f86f/grocy-desktop/FrmMain.cs#L170

The dictionary / environment variable `PHP_FCGI_MAX_REQUESTS` is clearly added only once there, so I have no clue what's going on.

A maybe related problem was there a longer time ago (ref https://github.com/grocy/grocy-desktop/commit/44f9a6c5ebc33b51de6c4af37139b9e890b13eea). So are you sure to really use the [latest release v2.1.0](https://github.com/grocy/grocy-desktop/releases/tag/v2.1.0)?

**Comment by AtomicClown** [comment]
I've used release v2.1.0 almost exclusively, only other version I tried was 1.8.1 just to see if there was any difference. I have no idea what it could be, I select "Update" and let it try just in case but nothing changes.

It must be something on my end, but I have no idea what else could be tried beyond what I have. I've done a fresh install under those different circumstances several times to no avail. (And I'm a complete neophyte when it comes to codes and whatnot, unfortunately.)

**Comment by berrnd** [comment]
Well, sorry if it doesn't work, I gladly solve any reproducible bug, as since ever.

But that seems to be clearly not a reproducible bug and therefore this here is the wrong place as [mentioned in README](https://github.com/grocy/grocy-desktop#questions--help--bug-reports--feature-requests=).

**Comment by AtomicClown** [comment]
I guess I'll have to try the subreddit, then. I appreciate your consideration regardless, hopefully I can find some kind of solution. This project very much interests me. Thank you again for your time.
