### ISSUE TITLE
Bug: can't add new product via mobile app

### ISSUE THREAD

**Issue by dezok666** [grocy/grocy-desktop#46]
Hello, I'm having issues with adding new product via mobile app.
Steps to reproduce: 
1. Go to purchases
2. scan barcode
3. tap add new product
4. fill in necessary data
5. and here is the problem: app requires to provide Barcode and QU conversions, but those fields aren't editable with error "Product is not on the server".
![Screenshot_2023-06-11-10-50-21-30_ded3d01f237383c8e0209ace216d3455](https://github.com/grocy/grocy-desktop/assets/48985656/c426bd11-33fa-4326-9d5a-b0fd66e48350)

For the life of me, I can't figure out what I am doing wrong 

Mobile app version: 3.2.1
Grocy Version 3.3.2 
PHP Version 8.1.18
SQLite Version 3.34.1
OS Linux 5.15.93-sunxi #23.02.2 SMP Fri Feb 17 23:49:46 UTC 2023 armv7l

**Comment by berrnd** [comment]
None of the community contributed mobile apps are maintained here - based on _"OS Linux [...]"_, this can't even be related to grocy-desktop which is a **Windows** desktop application wrapper for Grocy.

**Comment by dezok666** [comment]
Damn, wrong project, thanks @berrnd
