### ISSUE TITLE
Can the admin in the assignment option when creating a task be changed to something else?

### ISSUE THREAD

**Issue by shuen2023** [grocy/grocy-desktop#47]
Sorry, I really don't know how to modify it.  I want to set admin to whatever name I want.

![Clip_20230810_131814](https://github.com/grocy/grocy-desktop/assets/133501179/1b223c87-582e-4b80-a12f-13e8a5581475)

**Comment by berrnd** [comment]
User management is disabled when using Grocy via Grocy Desktop, but let's rethink that for proper task/chore assignments and so on.

**Comment by shuen2023** [comment]
> 通过 Grocy Desktop 使用 Grocy 时，用户管理被禁用，但让我们重新考虑一下正确的任务/杂务分配等。
OK, thanks

**Comment by berrnd** [comment]
A change in Grocy itself was necessary for this, will be supported with Grocy v4.0.2 (I will also push a new Grocy Desktop release later today).

**Comment by shuen2023** [comment]
> 为此，Grocy 本身需要进行更改，Grocy v4.0.2 将支持 Grocy Desktop 中的用户编辑（今天晚些时候我还将推出新的 Grocy Desktop 版本）。

Thank you so much! You guys are the best!
