### ISSUE TITLE
Feature Request: Flatpak package (on Flathub)

### ISSUE THREAD

**Issue by rugk** [grocy/grocy-desktop#49]
It would be nice if you could publish this as a [flatpak](https://flatpak.org/) on [flathub](https://flathub.org/) e.g.

Flatpaks are a new software distribution mechanism for Linux distros, can thus installed on any distro and are easy to update. They are easy to install _and_ update and work on all Linux distros.
Also, if you publish it on _FlatHub_ you may grow your user base given many distros include that and it is a common software source, so your app can be discovered more easily. 

Here is [how to get started](http://docs.flatpak.org/en/latest/getting-started.html).

**Comment by berrnd** [comment]
> Flatpaks are a new software distribution mechanism for Linux distros

Well, are you a user of Grocy Desktop or even had a little visit to [README](https://github.com/grocy/grocy-desktop#readme) beforehand? Sounds to be not the case, since Grocy Desktop is a Windows-only application, so this request makes not any sense at all.

**Comment by rugk** [comment]
Ohhh, I thought that would be cross-platform. That is sad…

And given the dependency on Microsoft UWP or what it uses it cannot be made cross-platform in an easy way?

Okay saw https://github.com/grocy/grocy-desktop/issues/7 well… .NET (Core) is cross-platform in any case. Windows Forms likely not so that is likely still an issue hmm…

**Comment by berrnd** [comment]
As already mentioned in #7, #37 and #44 - currently technically impossible (if you're also a C# / .Net top-notch expert, feel free to proof me wrong), at least it would need a whole other approach and Grocy Desktop will not be extend in that way.

&nbsp;
> Ohhh, I thought that would be cross-platform. 

[README](https://github.com/grocy/grocy-desktop#readme) excerpt (of the first line below the title):

_A (**Windows**) desktop application wrapper for [Grocy](https://github.com/grocy/grocy)_
---^^^^^^-----------
