### ISSUE TITLE
Bug: Desktop App crashes after install

### ISSUE THREAD

**Issue by Byacono1990** [grocy/grocy-desktop#53]
I downloaded the desktop app version and it either crashes or throws an error.

Install method: via microsoft store and via weblink install from Grocy.info

Error: FileNotFoundException
Exception Message: CefSettings.BrowserSubprocessPath not found.
Exception Stacktrace:
   at CefSharp.Core.Cef.Initialize(CefSettingsBase cefSettings, Boolean performDependencyCheck, IApp cefApp)
   at CefSharp.Cef.Initialize(CefSettingsBase settings, Boolean performDependencyCheck, IBrowserProcessHandler browserProcessHandler)
   at GrocyDesktop.FrmMain.SetupCef()
   at GrocyDesktop.FrmMain.<FrmMain_Shown>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
--------------------------------------------------------------------------------------------------------------
Crashing
loads home screen but if anything else is clicked, it goes to a black screen and then crashes.

Troubleshooting:
uninstalled and reinstalled
installed from alternative resource (i tried direct from gorcy first and then after attempts uninstall/reinstall and repair filed, i tried the microsoft store app version)
Microst options to repair and reset data

no luck.

![image](https://github.com/user-attachments/assets/6d354ad4-ef9d-4c6f-b855-e056480659c7)

**Comment by berrnd** [comment]
Not reproducible (each and every release is tested on standard and latest Windows 10 and Windows 11 machines), so more than clearly not a bug. And also happened not the first time, please be so kind and check around here and the internet. Most likely fancy antimalware software interferes and removes or blocks required dependency DLLs.

**Comment by GeorgeAston** [comment]
I have a similar issue. I installed Grocy on my Windows 10 machine about 3 weeks ago, worked fine for 2 days, and produced the error: 
![image](https://github.com/user-attachments/assets/8d44fbd7-7d0a-49c2-a461-166afbbe2542)
I have since tried again (after seeing that a newer update was available on GitHub), but I am still having the same issue after changing the location of the config-dist.php to config.php. 

Any thoughts on this would be brilliant! 

Many thanks in advance.

**Comment by berrnd** [comment]
> I have a similar issue. 

No, not a little tiny bit related to OP's reported "problem".

&nbsp;
> changing the location of the config-dist.php to config.php

Grocy Desktop auto manages everything needed to properly run Grocy. When you manually fiddle with stuff, that can produce problems of any kind without that much surprise. If you want to fiddle with stuff, such an automated way to run Grocy is most likely not what you're looking for. And if you mean you really removed `config-dist.php` or renamed it to `config.php`, what was the plan on that at all? Start over completely, restore your backup, or something like that.

In any case, not a reproducible bug, not a feature request ([README ref](https://github.com/grocy/grocy-desktop?tab=readme-ov-file#questions--help--bug-reports--feature-requests)), not related to what was originally mentioned here, so we're definitely done here.
